<?php $acao = $this->view->acao;?>
<section class="painel">
    <div class="form-style-2">
        <div class="form-style-2-heading"><label><span>&nbsp;</span><?php echo $this->view->nome?></label></div>
        <form enctype="multipart/form-data" action="/user/<?php echo ($acao == 'edit') ? 'update' : 'store'; ?>" method="post" accept-charset="utf-8">
            <?php if($acao == 'edit'){ ?>
                <input hidden type="text" name="id" value ="<?php echo $this->view->user->id; ?>" class="input-field" />
            <?php } ?>
            <div class="item">
                <label for="nome"><span>Nome</span>
                    <input <?php if($acao == 'detalhar') echo 'readonly'; ?> type="text" name="nome"
                        <?php
                            if($this->view->acao == 'edit'){
                                echo 'value="' . $this->view->user->nome . '"';
                            } else{
                                if(isset($this->inputs['nome']) && !empty($this->inputs['nome'])){
                                    echo 'value="' . $this->inputs['nome'] . '"';
                                } else {
                                    echo 'placeholder="nome completo"';
                                }
                            }
                        ?>
                    class="input-field" />
                </label>
                <?php if ($this->errors['nome']): ?>
                    <label><span>&nbsp;</span>
                        <p class="help-block"><?php echo $this->errors['nome'] ?></p>
                    </label>
                <?php endif; ?>
            </div>
            <div class="item">
                <label for="email"><span>E-mail</span>
                    <input <?php if($acao == 'detalhar') echo 'readonly'; ?> type="text" name="email"
                        <?php
                        if($this->view->acao == 'edit'){
                            echo ' readonly value="' . $this->view->user->email . '"';
                        } else{
                            if(isset($this->inputs['email']) && !empty($this->inputs['email'])){
                                echo 'value="' . $this->inputs['email'] . '"';
                            } else {
                                echo 'placeholder="email"';
                            }
                        }
                        ?>
                    class="input-field" />
                </label>
                <?php if ($this->errors['email']): ?>
                    <label><span>&nbsp;</span>
                        <p class="help-block"><?php echo $this->errors['email'] ?></p>
                    </label>
                <?php endif; ?>
            </div>
            <div class="item">
                <label for="urlfoto"><span>Escolha Uma Foto Bonita</span>
                    <input type="file" name="urlfoto" class="input-field" />
                </label>
            </div>
            <div class="item">
                <label for="graduacao"><span>Graduação</span>
                    <input <?php if($acao == 'detalhar') echo 'readonly'; ?> type="text" name="graduacao"
                        <?php
                            if($this->view->acao == 'edit'){
                                echo 'value="' . $this->view->user->graduacao . '"';
                            } else {
                                if (isset($this->inputs['graduacao']) && !empty($this->inputs['graduacao'])) {
                                    echo 'value="' . $this->inputs['graduacao'] . '"';
                                } else {
                                    echo 'placeholder="graduacao"';
                                }
                            }
                        ?>
                    class="input-field" />
                </label>
                <?php if ($this->errors['graduacao']): ?>
                    <label><span>&nbsp;</span>
                        <p class="help-block"><?php echo $this->errors['graduacao'] ?></p>
                    </label>
                <?php endif; ?>
            </div>
            <div class="item">
                <label for="dtnasc"><span>Data Nascimento</span>
                    <input <?php if($acao == 'detalhar') echo 'readonly'; ?> type="text" name="dtnasc"
                        <?php
                            if($this->view->acao == 'edit'){
                                echo 'value="' . implode('/', array_reverse(explode('-', $this->view->user->dtnasc))) . '"';
                            } else {
                                if (isset($this->inputs['dtnasc']) && !empty($this->inputs['dtnasc'])) {
                                    echo 'value="' . $this->inputs['dtnasc'] . '"';
                                } else {
                                    echo 'placeholder="dd/mm/aaaa"';
                                }
                            }
                        ?>
                    class="input-field" />
                </label>
                <?php if ($this->errors['dtnasc']): ?>
                    <label><span>&nbsp;</span>
                        <p class="help-block"><?php echo $this->errors['dtnasc'] ?></p>
                    </label>
                <?php endif; ?>
            </div>

            <div class="item">
                <label for="password"><span>Password</span>
                    <input type="password" name="password" placeholder="password" class="input-field" />
                </label>
                <?php if ($this->errors['password']): ?>
                    <label><span>&nbsp;</span>
                        <p class="help-block"><?php echo $this->errors['password'] ?></p>
                    </label>
                <?php endif; ?>
            </div>
            <?php
            if(!in_array($acao, array('edit','detalhar'))) { ?>
                <div class="item">
                    <label for=""><span>Tipo Usuário</span>
                        <select class="select-field" name="tipo">
                            <option value="1">Admin</option>
                            <option value="2" selected>Comum</option>
                        </select>
                    </label>
                </div>
                <?php
            } else {?>
                <div class="item">
                    <label for=""><span>Tipo Usuário</span>
                        <select class="select-field" name="tipo" <?php echo ($acao == 'detalhar') ? 'disabled' : ''?>>
                            <option value="1" <?php echo ($this->view->user->tipo == 1) ? 'selected' : '' ?>>Admin</option>
                            <option value="2" <?php echo ($this->view->user->tipo == 2) ? 'selected' : '' ?>>Comum</option>
                        </select>
                    </label>
                </div>
                <?php
            }?>

            <?php if(in_array($acao, array('edit','create'))) { ?>
                <div class="item">
                    <label for=""><span>&nbsp</span>
                        <input type="submit" value="<?php echo ($acao == 'edit') ? 'Editar' : 'Criar'?>" />
                    </label>
                </div>
            <?php }?>
        </form>
    </div>
</section>

