<div>
    <div>
        <h1><?php echo $this->view->nome ?></h1>
        <?php
            $this->renderView('alerts/_success');
            $this->renderView('alerts/_errors');
        ?>
    </div>
    <div id="about">
        </br>
        <h1 id="title1"> Seja Bem-vindo(a)!</h1></br></br></br>
        <p id="welcome" class="text-justify">
            Estamos ansiosos para conhecer melhor suas opniões e como você enxerga o mundo, pois com certeza será uma valiosa aquisição ter você em nosso forum de discussões.</br>

            Felizmente sempre haveŕa alguém que discorde de você, por isso aproveite as oportunidades para conversa e debater. Aqui você encontrará todo o apoio e iniciativa para continuar discutindo e conversando sobre todos os assuntos que necessite desde que prese pelo respeito ao próximo!</br></br></br>

            <p id="title1">
            "Sim, curvo-me ante a beleza de ser<br/>
            às vezes zombo de mim mesmo ao término de uma<br/>
            inteligente e aguçada constatação.<br/>
            Ermitão do insólito, poeta da dúvida<br/>
            Entretanto duvido a dúvida por ser dúvida<br/>
            fruto de uma premissa lógica<br/>
            Mas nego, afirmo e não duvido de nada<br/>
            Prisioneiro sem grade desse silêncio eterno."</br></br>
            <h4 id="author">Raul Seixas</h4>
            </p>
            </br></br>
        </p>
    </div>
</div>
