
    <?php if($this->auth->check()){?>
        <span class="float-right">
            Olá <?php echo $this->auth->name();?>
        </span>
    <?php } ?>
<div>
    <div>
        <h1><?php echo $this->view->nome ?></h1>
        <?php
            $this->renderView('alerts/_success');
            $this->renderView('alerts/_errors');
        ?>
    </div>
    <div>
        <p class="text-justify">
					Página em construção.
        </p">
    </div>
</div>
