-- MySQL Script generated by MySQL Workbench
-- Seg 05 Mar 2018 18:39:31 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema forumufba
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema forumufba
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `forumufba` DEFAULT CHARACTER SET utf8 ;
USE `forumufba` ;

-- -----------------------------------------------------
-- Table `forumufba`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `forumufba`.`users` ;

CREATE TABLE IF NOT EXISTS `forumufba`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NULL,
  `email` VARCHAR(100) NULL,
  `password` VARCHAR(100) NULL,
  `graduacao` VARCHAR(255) NULL COMMENT 'Texto livre para informar graduação/nível instrução do usuário\n',
  `dtnasc` DATE NULL COMMENT 'Data de nascimento\n',
  `urlfoto` VARCHAR(255) NULL,
  `pontos` INT NULL DEFAULT 0,
  `tipo` INT NULL COMMENT '1 - admin\n2 - usuario\n',
  `verificado` TINYINT(1) NULL DEFAULT false,
  'ativo' TINYINT(1) NULL DEFAULT  true,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `index2` (`email` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `forumufba`.`publications`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `forumufba`.`publications` ;

CREATE TABLE IF NOT EXISTS `forumufba`.`publications` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tema` VARCHAR(100) NULL,
  `titulo` VARCHAR(100) NULL,
  `conteudo` TEXT NULL,
  `visivel` INT NULL COMMENT '0 - nao visivel\n1 - visivel\n',
  `data` DATE NULL,
  `id_user` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_publications_1_idx` (`id_user` ASC),
  CONSTRAINT `fk_publications_1`
    FOREIGN KEY (`id_user`)
    REFERENCES `forumufba`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `forumufba`.`references`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `forumufba`.`references` ;

CREATE TABLE IF NOT EXISTS `forumufba`.`references` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `origem` VARCHAR(255) NULL COMMENT 'Texto livre para colocar livros ou links de outras publicações\n',
  `id_publication` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_references_1_idx` (`id_publication` ASC),
  CONSTRAINT `fk_references_1`
    FOREIGN KEY (`id_publication`)
    REFERENCES `forumufba`.`publications` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `forumufba`.`essays`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `forumufba`.`essays` ;

CREATE TABLE IF NOT EXISTS `forumufba`.`essays` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(255) NULL,
  `conteudo` TEXT NULL,
  `posicao` INT NULL DEFAULT 0 COMMENT '1 - favor\n0 - neutro\n-1 - contra\n',
  `id_publication` INT NULL,
  `id_user` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_essays_1_idx` (`id_publication` ASC),
  INDEX `fk_essays_2_idx` (`id_user` ASC),
  CONSTRAINT `fk_essays_1`
    FOREIGN KEY (`id_publication`)
    REFERENCES `forumufba`.`publications` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_essays_2`
    FOREIGN KEY (`id_user`)
    REFERENCES `forumufba`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `forumufba`.`reports`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `forumufba`.`reports` ;

CREATE TABLE IF NOT EXISTS `forumufba`.`reports` (
  `id` INT AUTO_INCREMENT,
  `id_essay` INT NULL,
  `id_user` INT NULL,
  `conteudo` TEXT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_reports_1_idx` (`id_essay` ASC),
  INDEX `fk_reports_2_idx` (`id_user` ASC),
  CONSTRAINT `fk_reports_1`
    FOREIGN KEY (`id_essay`)
    REFERENCES `forumufba`.`essays` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reports_2`
    FOREIGN KEY (`id_user`)
    REFERENCES `forumufba`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `forumufba`.`essay_avaliation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `forumufba`.`essay_avaliation` ;

CREATE TABLE IF NOT EXISTS `forumufba`.`essay_avaliation` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `avaliacao` INT NULL COMMENT '1 : positiva | (-1) : negativa\n',
  `id_essay` INT NULL,
  `id_user` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `index4` (`id_user` ASC, `id_essay` ASC),
  INDEX `fk_essay_avaliation_1_idx` (`id_essay` ASC),
  CONSTRAINT `fk_essay_avaliation_1`
    FOREIGN KEY (`id_essay`)
    REFERENCES `forumufba`.`essays` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_essay_avaliation_2`
    FOREIGN KEY (`id_user`)
    REFERENCES `forumufba`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `forumufba`.`essay_link`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `forumufba`.`essay_link` ;

CREATE TABLE IF NOT EXISTS `forumufba`.`essay_link` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `url` VARCHAR(255) NULL,
  `id_essay` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_essay_link_1_idx` (`id_essay` ASC),
  CONSTRAINT `fk_essay_link_1`
    FOREIGN KEY (`id_essay`)
    REFERENCES `forumufba`.`essays` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `forumufba`.`essay_oposition`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `forumufba`.`essay_oposition` ;

CREATE TABLE IF NOT EXISTS `forumufba`.`essay_oposition` (
  `id_essay` INT NULL,
  `id_essay_oposition` INT NULL,
  INDEX `fk_essay_oposition_1_idx` (`id_essay` ASC),
  INDEX `fk_essay_oposition_2_idx` (`id_essay_oposition` ASC),
  CONSTRAINT `fk_essay_oposition_1`
    FOREIGN KEY (`id_essay`)
    REFERENCES `forumufba`.`essays` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_essay_oposition_2`
    FOREIGN KEY (`id_essay_oposition`)
    REFERENCES `forumufba`.`essays` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_estonian_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
