<nav>
    <header>
        <ul class="float-left">
            <li><a href="/">Home</a></li>
            <li><a href="/forum">Forum</a></li>
            <?php if($this->auth->check()){?>
                <li><a href="/logout">Logout</a></li>
            <?php } else { ?>
                <li><a href="/login">Sing in</a></li>
                <li><a href="/user/create">Register</a></li>
            <?php } ?>
        </ul>
    </header>
</nav>
