<header class="clearfix">
    <div class="menu">
        <div class="header-right">
            <label for="open">
                <span class="hidden-desktop"></span>
            </label>
            <input type="checkbox" name="" id="open">
            <nav>
                <a href="/">Home</a>
                <a href="/forum">Forum</a>
                <?php if($this->auth->check()){?>
                    <a href="/logout">Logout</a>
                <?php } else { ?>
                    <a href="/login">Sing in</a>
                    <a href="/user/create">Register</a>
                <?php } ?>
            </nav>
        </div>
    </div>
</header>
