<section class="painel">
    <div class="caption"><?php echo $this->view->nome;?></div>
    <div id="table">
        <div class="header-row row">
            <span class="cell">Título</span>
            <span class="cell">Conteúdo</span>
            <span class="cell">Ação</span>
        </div>
        <?php foreach ($this->view->essay as $essay) { ?>
            <div class="row">
                <span class="cell" data-label="titulo"><?php echo substr($essay->titulo,0,25) . "..."; ?></span>
                <span class="cell" data-label="conteudo"><?php echo substr(strip_tags($essay->conteudo),0,25) . "..."; ?></span>
                <span class="cell" data-label="content">
                    <button class="button">
                        <a href="/publication/<?php echo $essay->id; ?>/detalhar"> <?php echo 'Detalhar' ?></a>
                    </button>
                    <button class="button button-green">
                        <a href="/essay/<?php echo $essay->id; ?>/edit"> <?php echo 'Editar' ?></a>
                    </button>
                    <button class="button button-red disabled">
                        <?php if(isset($publication->essays) && $publicantion->essays == 0){ ?>
                            <a href="/essay/<?php echo $essay->id; ?>/delete" onclick="return confirm('Tem certeza que deseja apagar?')"> <?php echo 'Apagar' ?></a>
                        <?php } else {echo 'Disabled';} ?>
                    </button>
                </span>
            </div>
        <?php } ?>
    </div>
</section>
